// ********RoostGPT********
// Test generated by RoostGPT for test ReactTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Moves from '../../../src/components/moves/Moves';

describe('Moves component', () => {
  test('renders with default props', () => {
    const historyMock = [{ squares: Array(9).fill(null) }];
    const jumpToMock = jest.fn();
    const { getByText } = render(<Moves history={historyMock} jumpTo={jumpToMock} />);

    // Check if the component correctly renders "Go to game start"
    expect(getByText('Go to game start')).toBeInTheDocument();
  });

  test('calls jumpTo function with the correct index when a move button is clicked', () => {
    const historyMock = [{ squares: Array(9).fill(null) }, { squares: ['X', ...Array(8).fill(null)] }];
    const jumpToMock = jest.fn();
    const { getAllByRole } = render(<Moves history={historyMock} jumpTo={jumpToMock} />);
    const buttonList = getAllByRole('button');

    // Simulate button click for the second move (index 1)
    fireEvent.click(buttonList[1]);

    // Expect the jumpTo function to have been called with the index 1
    expect(jumpToMock).toHaveBeenCalledWith(1);
  });
});

