// ********RoostGPT********
// Test generated by RoostGPT for test ReactTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import GameInfo from '../../../src/components/game-info/GameInfo';

describe('GameInfo Component', () => {
  // Test case for when there's no winner and player X is next.
  test('displays the correct turn message for player X', () => {
    render(<GameInfo status="" winner={null} xIsNext={true} />);
    const message = screen.getByText("It's your turn, player X");
    expect(message).toBeInTheDocument();
  });

  // Test case for when there's a winner.
  test('displays the winning message when a winner is present', () => {
    render(<GameInfo status="Winner: X" winner="X" xIsNext={false} />);
    const message = screen.getByText("Nice! I won!");
    expect(message).toBeInTheDocument();
  });

  // Additional test cases can be added to cover other scenarios.
});

