// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting123 using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import GameInfo from '../../../components/game-info/GameInfo';

describe('GameInfo Component', () => {

  test('should display message for player X turn when no winner', () => {
    render(<GameInfo status={null} winner={null} xIsNext={true} />);
    expect(screen.getByText("It's your turn, player X")).toBeInTheDocument();
  });

  test('should display message for player O turn when no winner', () => {
    render(<GameInfo status={null} winner={null} xIsNext={false} />);
    expect(screen.getByText("Now you, player O!")).toBeInTheDocument();
  });

  test('should display winning message for player X', () => {
    render(<GameInfo status={'Winner: X'} winner={'X'} xIsNext={false} />);
    expect(screen.getByText("Nice! I won!")).toBeInTheDocument();
  });

  test('should display winning message for player O', () => {
    render(<GameInfo status={'Winner: O'} winner={'O'} xIsNext={true} />);
    expect(screen.getByText("Wohoo! I made it!")).toBeInTheDocument();
  });

  test('should include an image with alt text "Player X and Player O"', () => {
    render(<GameInfo status={null} winner={null} xIsNext={true} />);
    expect(screen.getByAltText("Player X and Player O")).toBeInTheDocument();
  });
  
});

