// ********RoostGPT********
// Test generated by RoostGPT for test ReactTesting123 using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, fireEvent } from '@testing-library/react';
import Square from '../../../../components/square/Square'; // Correct relative path for the import

// Test suite for Square component
describe('Square', () => {
  // Test case for checking if the Square component renders a button with the correct value
  test('renders a button with the provided value', () => {
    const value = 'X';
    const { getByText } = render(<Square value={value} onClick={() => {}} />);
    const buttonElement = getByText(value);
    expect(buttonElement).toBeInTheDocument();
  });

  // Test case to confirm that the Square's onClick handler gets called when clicked
  test('calls onClick event on click of the button', () => {
    const onClick = jest.fn(); // Mock function to test click handler
    const { getByText } = render(<Square value="X" onClick={onClick} />);
    fireEvent.click(getByText('X')); // Simulate a button click
    expect(onClick).toHaveBeenCalledTimes(1); // Assert that the handler was called once
  });

  // Add more tests as necessary...
});

