// ********RoostGPT********
// Test generated by RoostGPT for test ReactTest using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import Square from '../../../src/components/square/Square';

// Test suite for the Square component
describe('Square', () => {
  // Test case 1: should render a button with the square class
  test('renders a button', () => {
    const { getByRole } = render(<Square />);
    expect(getByRole('button')).toBeInTheDocument();
    expect(getByRole('button')).toHaveClass('square');
  });

  // Test case 2: should display value prop inside the button
  test('displays value prop inside button', () => {
    const value = 'X';
    render(<Square value={value} />);
    expect(screen.getByRole('button')).toHaveTextContent(value);
  });

  // Test case 3: should call onClick prop when button is clicked
  test('calls onClick prop when clicked', () => {
    const handleClick = jest.fn();
    render(<Square onClick={handleClick} />);

    fireEvent.click(screen.getByRole('button'));
    expect(handleClick).toHaveBeenCalledTimes(1);
  });
});

